/**
 * Education Module Data
 * 3 modules (prime), 3 voices each (Tesla's 3).
 * Poetic + Both: 7 pages (prime). Science: 5 pages (prime).
 * Pages per module: 19 (prime). Total: 57 pages.
 * Arc: Validation > Understanding > Hope.
 * Colour: emerald (#00ff41) — 396Hz, liberation from fear.
 */

export const VOICE_KEYS = ['poetic', 'science', 'both'];

export const EDUCATION_MODULES = [
  {
    slug: 'your-nervous-system',
    title: 'Your Nervous System',
    description: 'What actually happens when sound hurts.',
    duration: '~3 min',
    voices: {
      poetic: {
        name: 'Feel It',
        description: 'the version that lands in your body.',
        duration: '~3 min',
        pages: [
          {
            lines: [
              'your brain has a guard at the gate.',
              '',
              'it has been standing there',
              'since before you could speak.',
              'since before you had words for fear.',
              '',
              'it is very good at its job.',
            ],
          },
          {
            lines: [
              'the sound arrives',
              'and before you can think,',
              'your whole body says',
              { text: 'run.', dramatic: true },
              '',
              'this is not a choice you are making.',
              'this is not weakness.',
              '',
              'this is a protector, working overtime.',
            ],
          },
          {
            lines: [
              'you might notice, as you read this,',
              'something in your chest.',
              '',
              'a tightness. a holding.',
              '',
              'that part of you that holds on',
              'is the same part that reacts to sound.',
              '',
              'it is trying to keep you safe.',
            ],
          },
          {
            lines: [
              'there is a part of you that reacts.',
              '',
              { text: 'that part is not broken.', dramatic: true },
              '',
              'it is a protector working overtime.',
              'it learned a long time ago',
              'that certain sounds meant danger.',
              '',
              'it has been doing its job ever since.',
            ],
          },
          {
            lines: [
              'notice your jaw right now.',
              '',
              'let it soften.',
              '',
              'notice your shoulders.',
              '',
              'perhaps they can drop,',
              'just a little.',
              '',
              'your nervous system is listening.',
              'it always is.',
            ],
          },
          {
            lines: [
              'your nervous system is not failing you.',
              '',
              { text: 'it is doing exactly what it was designed to do.', dramatic: true },
              '',
              'the signal is real.',
              'the wiring is real.',
              'the pain is real.',
              '',
              'you were never making it up.',
            ],
          },
          {
            lines: [
              'and perhaps you are already',
              'beginning to notice',
              'that something here',
              { text: 'feels different.', dramatic: true },
              '',
              'your body knows the difference',
              'between being told to "get over it"',
              'and being told: you are not broken.',
              '',
              'you are not broken.',
            ],
          },
        ],
      },
      science: {
        name: 'Know It',
        description: 'the version that satisfies your mind.',
        duration: '~2 min',
        pages: [
          {
            lines: [
              'your amygdala responds',
              'in approximately 12 milliseconds.',
              '',
              { text: 'faster than conscious thought.', dramatic: true },
              '',
              'that is why it feels like ambush.',
              'your threat detector fires',
              'before your thinking brain',
              'even knows the sound is there.',
            ],
          },
          {
            lines: [
              'Kumar et al., 2017.',
              'Newcastle University.',
              '',
              'they found the anterior insular cortex',
              'hyper-activates in response',
              'to trigger sounds.',
              '',
              'this region connects three things:',
              'sound, emotion, and body.',
              '',
              'when it fires, all three fire together.',
              'that is why it feels like your whole self reacts.',
            ],
          },
          {
            lines: [
              'this is not an auditory problem.',
              '',
              { text: 'your hearing is fine.', dramatic: true },
              '',
              'it is a threat-detection problem.',
              '',
              'Edelstein et al., 2011:',
              'mirror neurons simulate the action.',
              'chewing. clicking. sniffing.',
              '',
              'your motor cortex fires',
              'as if you were doing it yourself.',
            ],
          },
          {
            lines: [
              'this is measurable.',
              'fMRI. EEG. autonomic response.',
              '',
              { text: 'your response has a name and a mechanism.', dramatic: true },
              '',
              'it is not a personality flaw.',
              'it is not anxiety.',
              'it is a specific, identifiable',
              'neural pattern.',
            ],
          },
          {
            lines: [
              'and neuroplasticity means',
              'the circuit can change.',
              '',
              { text: 'that is not a metaphor.', dramatic: true },
              '',
              'Hebb, 1949: neurons that fire together',
              'wire together. it works both ways.',
              '',
              'the wiring is real.',
              'and the rewiring is possible.',
              'that is what the data shows.',
            ],
          },
        ],
      },
      both: {
        name: 'The Full Picture',
        description: 'both voices, woven together.',
        duration: '~3 min',
        pages: [
          {
            lines: [
              'your brain has a guard at the gate.',
              '',
              'neuroscientists call it the amygdala.',
              '',
              'it fires in twelve milliseconds.',
              'before you even know',
              'the sound is there.',
              '',
              { text: 'no wonder it feels like ambush.', dramatic: true },
            ],
          },
          {
            lines: [
              'in 2017, Kumar\'s team',
              'at Newcastle University',
              'put people in an fMRI scanner.',
              '',
              'they found a region called',
              'the anterior insular cortex.',
              'it connects sound, emotion, and body.',
              '',
              'when it fires, your whole self reacts.',
              'that is not dramatic.',
              'that is anatomy.',
            ],
          },
          {
            lines: [
              'there is a part of you',
              'that hears the sound',
              'and says: danger.',
              '',
              'Edelstein found that mirror neurons',
              'simulate the action.',
              'your brain does not just hear chewing.',
              { text: 'it feels like you are doing it.', dramatic: true },
              '',
              'no wonder your body revolts.',
            ],
          },
          {
            lines: [
              'notice your jaw right now.',
              'let it soften.',
              '',
              'that tension is your nervous system',
              'doing what the research describes:',
              'connecting sound to body,',
              'body to emotion.',
              '',
              'it is real. it is measurable.',
              'and it is not your fault.',
            ],
          },
          {
            lines: [
              'you have a protector in your brain',
              'that learned to classify',
              'certain sounds as dangerous.',
              '',
              'the fMRI proves the signal is real.',
              '',
              { text: 'the danger is not.', dramatic: true },
              '',
              'and that difference matters.',
            ],
          },
          {
            lines: [
              'your nervous system learned this response.',
              '',
              'Hebb\'s law: neurons that fire together',
              'wire together.',
              '',
              'but Hebb\'s law works both ways.',
              '',
              'anything that was learned',
              'can be reshaped.',
              'that is not hope. that is neuroscience.',
            ],
          },
          {
            lines: [
              { text: 'you are not broken.', dramatic: true },
              '',
              'Kumar\'s team proved the wiring is real.',
              'and Hebb\'s law proves it can change.',
              '',
              'your body already knows this.',
              '',
              { text: 'that is why you are here.', dramatic: true },
            ],
          },
        ],
      },
    },
  },
  {
    slug: 'why-breathwork-works',
    title: 'Why Breathwork Works',
    description: 'The science of why breath changes everything.',
    duration: '~3 min',
    voices: {
      poetic: {
        name: 'Feel It',
        description: 'the version that lands in your body.',
        duration: '~3 min',
        pages: [
          {
            lines: [
              'you have been holding your breath',
              'your whole life',
              'and calling it normal.',
              '',
              'you might not even notice it.',
              '',
              'but your body notices.',
              { text: 'your body always notices.', dramatic: true },
            ],
          },
          {
            lines: [
              'there is a difference between',
              '"just breathe"',
              'and understanding why.',
              '',
              'you have probably been told',
              'to calm down.',
              '',
              'that is not what this is.',
              '',
              'this is: what if your body',
              'already knows the way home?',
            ],
          },
          {
            lines: [
              'you breathe out',
              'and something remembers',
              'how to be still.',
              '',
              'not because you forced it.',
              'not because you told it to.',
              '',
              { text: 'because the exhale is an invitation.', dramatic: true },
              '',
              'and your body has been waiting',
              'for the invitation.',
            ],
          },
          {
            lines: [
              'the part of you that holds your breath',
              'is the same part that holds you together.',
              '',
              'it has been gripping',
              'since before you knew why.',
              '',
              'what if you could let it rest?',
              '',
              'not by fighting it.',
              { text: 'by breathing beside it.', dramatic: true },
            ],
          },
          {
            lines: [
              'notice where the breath lands.',
              '',
              'not where you send it.',
              'where it goes on its own.',
              '',
              'your chest. your belly.',
              'the space behind your ribs.',
              '',
              'that is your body,',
              'showing you what it needs.',
            ],
          },
          {
            lines: [
              'you do not need to breathe perfectly.',
              '',
              'you do not need to count perfectly.',
              '',
              'you just need to exhale',
              'a little longer than you inhale.',
              '',
              { text: 'that is enough.', dramatic: true },
              '',
              'that has always been enough.',
            ],
          },
          {
            lines: [
              'and as you continue to breathe,',
              'you might find yourself',
              { text: 'already knowing why this matters.', dramatic: true },
              '',
              'not because someone explained it.',
              '',
              'because your body proved it.',
              '',
              'one exhale at a time.',
            ],
          },
        ],
      },
      science: {
        name: 'Know It',
        description: 'the version that satisfies your mind.',
        duration: '~2 min',
        pages: [
          {
            lines: [
              'the vagus nerve.',
              '',
              'the longest nerve in your body.',
              'brainstem to gut.',
              '',
              { text: 'your emergency brake.', dramatic: true },
              '',
              'it controls heart rate,',
              'digestion, inflammation.',
              'and you can activate it',
              'with your breath.',
            ],
          },
          {
            lines: [
              'the mechanism is simple.',
              '',
              'when your exhale is longer',
              'than your inhale,',
              'the vagus nerve activates.',
              '',
              'Gerritsen & Band, 2018:',
              'breathing at 5-6 breaths per minute',
              'directly stimulates vagal tone.',
              '',
              'that is the parasympathetic shift.',
            ],
          },
          {
            lines: [
              'the 4-7-8 pattern.',
              '',
              '4 seconds in.',
              '7 seconds hold.',
              '8 seconds out.',
              '',
              'the longest phase is the exhale.',
              { text: 'parasympathetic dominance by design.', dramatic: true },
              '',
              'respiratory sinus arrhythmia.',
              'your heart rate literally slows',
              'on the exhale.',
            ],
          },
          {
            lines: [
              'measurable outcomes:',
              '',
              'reduced cortisol.',
              'increased heart rate variability.',
              'autonomic shift from',
              'sympathetic to parasympathetic.',
              '',
              { text: 'not a metaphor. data.', dramatic: true },
            ],
          },
          {
            lines: [
              'your body already does this.',
              '',
              'the physiological sigh.',
              'a double inhale, long exhale.',
              'you do it naturally',
              'before sleep, after crying.',
              '',
              'you are not learning',
              'something new.',
              { text: 'you are learning to use it on purpose.', dramatic: true },
            ],
          },
        ],
      },
      both: {
        name: 'The Full Picture',
        description: 'both voices, woven together.',
        duration: '~3 min',
        pages: [
          {
            lines: [
              'there is a nerve that runs',
              'from your skull to your stomach.',
              '',
              'scientists call it the vagus nerve.',
              '',
              { text: 'your body calls it the way home.', dramatic: true },
            ],
          },
          {
            lines: [
              'you have been told to "just breathe."',
              '',
              'and you wanted to scream.',
              '',
              'that is a reasonable response',
              'to unhelpful advice.',
              '',
              'but there is a mechanism here',
              'worth understanding.',
            ],
          },
          {
            lines: [
              'when your exhale is longer',
              'than your inhale,',
              'something shifts.',
              '',
              'Gerritsen & Band measured it in 2018.',
              '',
              'but your grandmother already knew it',
              'when she said',
              { text: 'take a deep breath.', dramatic: true },
            ],
          },
          {
            lines: [
              'the 4-7-8 pattern is not arbitrary.',
              '',
              '4 in. 7 hold. 8 out.',
              'the longest phase is the exhale.',
              '',
              'that is not a design choice.',
              'it is how your vagus nerve works.',
              '',
              'parasympathetic dominance.',
              'your heart rate slows on the exhale.',
              'measurable. reproducible.',
            ],
          },
          {
            lines: [
              'notice your breath right now.',
              '',
              'not where you send it.',
              'where it goes on its own.',
              '',
              'that is your body,',
              'doing what the research describes.',
              '',
              'reduced cortisol.',
              'increased heart rate variability.',
              { text: 'the science feels like relief.', dramatic: true },
            ],
          },
          {
            lines: [
              'your body already does this.',
              '',
              'the physiological sigh.',
              'a double inhale, long exhale.',
              'you do it before sleep.',
              'after crying.',
              '',
              'you have always known',
              'what your nervous system needs.',
              'now you know why.',
            ],
          },
          {
            lines: [
              { text: 'one exhale at a time.', dramatic: true },
              '',
              'that is not a platitude.',
              'it is a mechanism.',
              '',
              'and now you know both.',
              '',
              'the feeling, and the reason.',
              'the body, and the proof.',
            ],
          },
        ],
      },
    },
  },
  {
    slug: 'your-brain-can-learn',
    title: 'Your Brain Can Learn',
    description: 'How your nervous system builds new pathways.',
    duration: '~3 min',
    voices: {
      poetic: {
        name: 'Feel It',
        description: 'the version that lands in your body.',
        duration: '~3 min',
        pages: [
          {
            lines: [
              'imagine a forest',
              'where every sound',
              'carved the same trail.',
              '',
              'deeper, faster, automatic.',
              '',
              'but beside that trail,',
              { text: 'there is space for a new one.', dramatic: true },
            ],
          },
          {
            lines: [
              '"you are stuck with this."',
              '"it only gets worse."',
              '',
              'you have probably heard both.',
              '',
              'those are stories.',
              'told by people who did not know',
              'what was possible.',
              '',
              { text: 'you are not those stories.', dramatic: true },
            ],
          },
          {
            lines: [
              'every breath you take',
              'through this app',
              'is a footstep.',
              '',
              'every moment of grounding',
              'is a clearing in the forest.',
              '',
              'you might not see the path yet.',
              'but it is forming.',
            ],
          },
          {
            lines: [
              'the old path was built',
              'by a part of you',
              'that was trying to survive.',
              '',
              { text: 'that part did its job.', dramatic: true },
              '',
              'and now another part',
              'is ready to build something new.',
              '',
              'not by destroying the old path.',
              'by growing beside it.',
            ],
          },
          {
            lines: [
              'notice your hands right now.',
              '',
              'are they holding anything?',
              'tension. a phone. a fist.',
              '',
              'what if you could soften them.',
              'just 5% more.',
              '',
              { text: 'that is how change works.', dramatic: true },
              'not all at once. 5% at a time.',
            ],
          },
          {
            lines: [
              'you do not need to be healed.',
              '',
              'you just need 5% more space',
              'between the sound',
              'and the storm.',
              '',
              'that is not a small thing.',
              { text: 'that is everything.', dramatic: true },
            ],
          },
          {
            lines: [
              'when you notice the change',
              'and you will',
              'it will feel less like fixing',
              { text: 'and more like remembering.', dramatic: true },
              '',
              'remembering what your body knows',
              'when it is not afraid.',
              '',
              'you are already on the path.',
            ],
          },
        ],
      },
      science: {
        name: 'Know It',
        description: 'the version that satisfies your mind.',
        duration: '~2 min',
        pages: [
          {
            lines: [
              'neuroplasticity.',
              '',
              'neurons that fire together,',
              'wire together.',
              'Hebb, 1949.',
              '',
              { text: 'it works both ways.', dramatic: true },
              '',
              'the old pattern was learned.',
              'a new pattern can be built.',
            ],
          },
          {
            lines: [
              'Pascual-Leone, 1995.',
              'Harvard Medical School.',
              '',
              'two groups learned piano.',
              'one practised physically.',
              'one only imagined practising.',
              '',
              'both groups developed',
              { text: 'the same neural pathways.', dramatic: true },
              '',
              'imagination builds real circuits.',
            ],
          },
          {
            lines: [
              'Holzel et al., 2011.',
              '',
              '8 weeks of meditation',
              'measurably reduced',
              'amygdala grey matter density.',
              '',
              { text: '8 weeks.', dramatic: true },
              '',
              'the threat detector itself changed.',
              'not suppressed. changed.',
            ],
          },
          {
            lines: [
              'every regulation practice is a rep.',
              'every rep changes the circuit.',
              '',
              'breathwork. grounding.',
              'body awareness.',
              '',
              'these are direct inputs',
              'to the brain regions',
              'that process threat.',
              '',
              { text: 'this is not hope. it is data.', dramatic: true },
            ],
          },
          {
            lines: [
              'the timeline is real.',
              '',
              'not overnight.',
              'not linear.',
              '',
              'but the pathways are forming',
              'whether you feel them or not.',
              '',
              'that is what the research shows.',
              { text: 'and the research is clear.', dramatic: true },
            ],
          },
        ],
      },
      both: {
        name: 'The Full Picture',
        description: 'both voices, woven together.',
        duration: '~3 min',
        pages: [
          {
            lines: [
              'neurons that fire together,',
              'wire together.',
              '',
              'that phrase is from a neuroscientist',
              'named Donald Hebb.',
              '',
              'but your body already knew it.',
              '',
              'every time you practised calm,',
              { text: 'it remembered.', dramatic: true },
            ],
          },
          {
            lines: [
              'imagine a forest.',
              '',
              'the old path was carved',
              'by repetition.',
              'neuroscientists would call it',
              'long-term potentiation.',
              '',
              'your body calls it',
              { text: 'the thing that happens every time.', dramatic: true },
              '',
              'but Hebb\'s law works both ways.',
            ],
          },
          {
            lines: [
              'at Harvard, Pascual-Leone',
              'taught people piano.',
              '',
              'one group practised.',
              'one group only imagined.',
              '',
              'both built the same pathways.',
              '',
              'every time you breathe here,',
              'you are building a real circuit.',
              'even when it does not feel like it.',
            ],
          },
          {
            lines: [
              'Holzel\'s team, 2011.',
              '',
              '8 weeks of meditation.',
              'the amygdala changed.',
              '',
              'not suppressed.',
              'not overridden.',
              { text: 'structurally changed.', dramatic: true },
              '',
              'the guard at the gate',
              'learned to stand down.',
            ],
          },
          {
            lines: [
              'notice your hands right now.',
              '',
              'are they holding anything?',
              '',
              'what if you could soften them.',
              'just 5%.',
              '',
              'that is what the neuroscience',
              'is really saying.',
              { text: 'tiny shifts. real pathways.', dramatic: true },
            ],
          },
          {
            lines: [
              'the timeline is real.',
              'not overnight. not linear.',
              '',
              'some days will feel like',
              'nothing moved.',
              '',
              'but underneath,',
              'the pathways are forming.',
              '',
              'Holzel proved it takes eight weeks.',
              'your body is already counting.',
            ],
          },
          {
            lines: [
              { text: 'you are not broken.', dramatic: true },
              '',
              'you are not stuck.',
              '',
              'Holzel proved the amygdala',
              'can change in eight weeks.',
              '',
              'and somewhere in your nervous system,',
              'that process has already begun.',
              '',
              { text: 'that is what you are here for.', dramatic: true },
            ],
          },
        ],
      },
    },
  },
];

/**
 * Find a module by slug
 */
export function getEducationModule(slug) {
  return EDUCATION_MODULES.find((m) => m.slug === slug) || null;
}

/**
 * Get pages for a specific voice of a module
 */
export function getVoicePages(slug, voiceKey) {
  const mod = getEducationModule(slug);
  return mod?.voices?.[voiceKey]?.pages || null;
}

/**
 * Light summary of a module (no voice content)
 */
export function getModuleSummary(slug) {
  const mod = getEducationModule(slug);
  if (!mod) return null;
  return { slug: mod.slug, title: mod.title, description: mod.description };
}
