import { ROUTES } from '@/lib/constants';

export const OUTER_REGULATION_PRACTICES = [
  {
    id: 'movement-reset',
    title: 'Movement Reset',
    family: 'movement',
    module: '2.5',
    status: 'ready',
    format: 'movement-practice',
    route: `${ROUTES.REGULATION_TOOLKIT}/movement-reset`,
    durationLabel: '89 sec',
    bestFor: ['anger', 'activation', 'stuck_energy'],
    bodySignals: ['Heat or flushing', 'Urge to escape', 'Fists clenching', 'Trembling'],
    discreteness: 'low',
    energyLevel: 'medium',
    solfeggio: 'cyan',
    summary: 'Shake, walk, or stretch to help activation move through.',
    steps: [
      'Choose shake, walk, or stretch.',
      'Move gently enough that you stay in control.',
      'Let the breath stay easy.',
      'Slow down before you stop.',
    ],
    safetyNotes: ['Choose a safe space. Do not use intense movement if you feel dizzy or unsafe.'],
  },
  {
    id: 'cold-water-micro-reset',
    title: 'Cold Water Micro Reset',
    family: 'movement',
    module: '2.5',
    status: 'ready',
    format: 'safety-checklist',
    route: `${ROUTES.REGULATION_TOOLKIT}/cold-water-micro-reset`,
    durationLabel: '34 sec',
    bestFor: ['daily_practice', 'resilience', 'state_shift'],
    bodySignals: ['Heat or flushing', 'Numbness'],
    discreteness: 'low',
    energyLevel: 'medium',
    solfeggio: 'slate',
    summary: 'A tiny cool-water reset for hands or face, never a shock challenge.',
    steps: [
      'Check that cold water feels appropriate today.',
      'Use cool water on hands or face.',
      'Keep breathing slowly.',
      'Warm yourself afterwards.',
    ],
    safetyNotes: ['Skip this during high stress, exhaustion, health concerns, or if your body says no.'],
  },
  {
    id: 'sound-support',
    title: 'Sound Support',
    family: 'sound',
    module: '2.5',
    status: 'ready',
    format: 'support-guide',
    route: `${ROUTES.REGULATION_TOOLKIT}/sound-support`,
    durationLabel: 'guide',
    bestFor: ['masking', 'public', 'recovery'],
    bodySignals: ['Urge to escape', 'Heart racing', 'Jaw tension'],
    discreteness: 'high',
    energyLevel: 'low',
    solfeggio: 'indigo',
    summary: 'Choose sound as support now, with less dependency as the long-term aim.',
    steps: [
      'Choose masking, music, nature sound, or quiet.',
      'Set volume as low as still feels supportive.',
      'Pair the sound with one slow breath.',
      'Check whether your body needs another practice too.',
    ],
    safetyNotes: ['Protect your hearing. This is support, not a test of endurance.'],
  },
  {
    id: 'emergency-protocol',
    title: 'Emergency Protocol',
    family: 'senses',
    module: '2.5',
    status: 'ready',
    format: 'protocol',
    route: `${ROUTES.REGULATION_TOOLKIT}/emergency-protocol`,
    durationLabel: 'now',
    bestFor: ['triggered_now', 'cannot_escape', 'high_intensity'],
    bodySignals: ['Urge to escape', 'Heart racing', 'Fists clenching', 'Trembling'],
    discreteness: 'high',
    energyLevel: 'low',
    solfeggio: 'slate',
    summary: 'A simple plan for intense trigger moments.',
    steps: [
      'Leave the situation if you safely can.',
      'Use one truthful phrase.',
      'If you cannot leave, return to the breath.',
      'Remind yourself this moment will pass.',
      'Choose one recovery practice afterwards.',
    ],
    safetyNotes: ['This is not about forcing yourself to endure unsafe situations.'],
  },
];
