import { ROUTES } from '@/lib/constants';

export const INNER_REGULATION_PRACTICES = [
  {
    id: 'physiological-sigh',
    toolId: '4',
    title: 'Physiological Sigh',
    family: 'breath',
    module: '2.4',
    status: 'ready',
    format: 'breath-player',
    route: `${ROUTES.TOOLS}/4?duration=quick`,
    durationLabel: '34 sec',
    bestFor: ['triggered_now', 'panic_spike', 'short_window'],
    bodySignals: ['Shallow breathing', 'Heart racing', 'Chest tightness'],
    discreteness: 'medium',
    energyLevel: 'low',
    solfeggio: 'indigo',
    summary: 'A double inhale and long exhale for a fast body reset.',
    steps: ['Breathe in through your nose.', 'Sip in a little more air.', 'Let the exhale be long and easy.'],
    safetyNotes: ['Keep it gentle. Stop if your breath feels strained.'],
  },
  {
    id: 'grounding-54321',
    title: '5-4-3-2-1 Grounding',
    family: 'senses',
    module: '2.4',
    status: 'ready',
    format: 'guided-experience',
    route: ROUTES.EXPERIENCE_GROUNDING,
    durationLabel: '3 min',
    bestFor: ['triggered_now', 'dissociation', 'overwhelm'],
    bodySignals: ['Numbness', 'Trembling', 'Urge to escape'],
    discreteness: 'high',
    energyLevel: 'low',
    solfeggio: 'cyan',
    summary: 'Use your senses to return to the room you are in.',
    steps: [
      'Notice five things you can see.',
      'Touch four things near you.',
      'Listen for three sounds that are not the trigger.',
      'Notice two scents, or imagine two safe scents.',
      'Notice one taste, or one slow breath.',
    ],
    safetyNotes: ['Eyes open is completely fine. This can be done quietly anywhere.'],
  },
  {
    id: 'butterfly-tapping',
    title: 'Butterfly Tapping',
    family: 'body',
    module: '2.4',
    status: 'ready',
    format: 'guided-practice',
    route: `${ROUTES.REGULATION_TOOLKIT}/butterfly-tapping`,
    durationLabel: '89 sec',
    bestFor: ['rumination', 'anticipation', 'after_trigger'],
    bodySignals: ['Fists clenching', 'Muscle tension', 'Heart racing'],
    discreteness: 'medium',
    energyLevel: 'low',
    solfeggio: 'violet',
    summary: 'A gentle left-right tapping rhythm to help your body settle.',
    steps: [
      'Cross your arms if that feels comfortable.',
      'Tap left, then right, slowly.',
      'Let your feet join the rhythm if you want.',
      'Breathe and notice the body without forcing a change.',
      'Let the tapping fade when you feel more here.',
    ],
    safetyNotes: ['This is self-regulation, not therapy. Keep the memory light and return to the room whenever you need.'],
  },
  {
    id: 'box-breathing',
    toolId: '3',
    title: 'Box Breathing',
    family: 'breath',
    module: '2.4',
    status: 'ready',
    format: 'breath-player',
    route: `${ROUTES.TOOLS}/3?duration=quick`,
    durationLabel: '1.5 min',
    bestFor: ['prepare', 'public', 'steadying'],
    bodySignals: ['Jaw tension', 'Muscle tension', 'Shallow breathing'],
    discreteness: 'high',
    energyLevel: 'low',
    solfeggio: 'cyan',
    summary: 'An even rhythm for balance and steadiness.',
    steps: ['Inhale for four.', 'Hold for four.', 'Exhale for four.', 'Hold for four.'],
    safetyNotes: ['Soften the holds if they feel uncomfortable.'],
  },
  {
    id: '478-breathing',
    toolId: '1',
    title: '4-7-8 Breathing',
    family: 'breath',
    module: '2.4',
    status: 'ready',
    format: 'breath-player',
    route: `${ROUTES.TOOLS}/1?duration=quick`,
    durationLabel: '1.5 min',
    bestFor: ['sleep', 'downshift', 'racing_mind'],
    bodySignals: ['Chest tightness', 'Shallow breathing', 'Heart racing'],
    discreteness: 'medium',
    energyLevel: 'low',
    solfeggio: 'indigo',
    summary: 'A longer exhale practice for evening and recovery.',
    steps: ['Inhale for four.', 'Hold for seven.', 'Exhale for eight.', 'Let the exhale do the work.'],
    safetyNotes: ['Use a shorter hold if your system is very activated.'],
  },
  {
    id: 'body-scan',
    title: 'Body Scan',
    family: 'body',
    module: '2.4',
    status: 'ready',
    format: 'guided-practice',
    route: `${ROUTES.REGULATION_TOOLKIT}/body-scan`,
    durationLabel: '233 sec',
    bestFor: ['after_trigger', 'body_awareness', 'before_sleep'],
    bodySignals: ['Jaw tension', 'Chest tightness', 'Stomach knot', 'Muscle tension'],
    discreteness: 'low',
    energyLevel: 'low',
    solfeggio: 'cyan',
    summary: 'Move attention through the body and notice what is asking for care.',
    voiceGuide: {
      status: 'recording_needed',
      recordingKey: 'regulation/body-scan/v1',
      totalDurationSec: 233,
      phases: [
        { id: 'feet', title: 'Feet and Ground', cue: 'Start at your feet and notice contact with the ground.', durationSec: 34 },
        { id: 'legs', title: 'Legs and Hips', cue: 'Move attention through your legs and hips without forcing release.', durationSec: 55 },
        { id: 'centre', title: 'Stomach and Chest', cue: 'Notice your stomach, chest, and shoulders with a softer breath.', durationSec: 55 },
        { id: 'face', title: 'Jaw and Face', cue: 'Soften your jaw, eyes, and forehead, or skip any area that feels unsafe.', durationSec: 55 },
        { id: 'whole', title: 'Whole Body', cue: 'Take one breath with the whole body and let the practice close gently.', durationSec: 34 },
      ],
    },
    steps: [
      'Start at your feet and notice contact with the ground.',
      'Move attention through your legs and hips.',
      'Notice your stomach, chest, and shoulders.',
      'Soften your jaw, eyes, and forehead.',
      'Take one breath with the whole body.',
    ],
    safetyNotes: ['Skip any body area you do not want to focus on.'],
  },
  {
    id: 'progressive-muscle-relaxation',
    title: 'Progressive Muscle Relaxation',
    family: 'body',
    module: '2.4',
    status: 'ready',
    format: 'guided-practice',
    route: `${ROUTES.REGULATION_TOOLKIT}/progressive-muscle-relaxation`,
    durationLabel: '233 sec',
    bestFor: ['tension', 'before_sleep', 'after_trigger'],
    bodySignals: ['Jaw tension', 'Fists clenching', 'Muscle tension'],
    discreteness: 'medium',
    energyLevel: 'low',
    solfeggio: 'violet',
    summary: 'Tense and release small muscle groups so the body remembers the difference.',
    voiceGuide: {
      status: 'recording_needed',
      recordingKey: 'regulation/progressive-muscle-relaxation/v1',
      totalDurationSec: 233,
      phases: [
        { id: 'hands', title: 'Hands', cue: 'Gently tense your hands, then let them release.', durationSec: 34 },
        { id: 'arms', title: 'Arms and Shoulders', cue: 'Lift your shoulders slightly, then let them drop down.', durationSec: 55 },
        { id: 'jaw', title: 'Jaw and Face', cue: 'Soften your jaw, tongue, eyes, and forehead.', durationSec: 55 },
        { id: 'belly', title: 'Belly and Hips', cue: 'Let the belly and hips release without pushing for calm.', durationSec: 55 },
        { id: 'breath', title: 'Release Breath', cue: 'Notice the difference between holding and letting go.', durationSec: 34 },
      ],
    },
    steps: ['Gently tense your hands.', 'Release and notice the change.', 'Lift your shoulders slightly.', 'Release your shoulders down.', 'Soften your jaw and let the breath widen.'],
    safetyNotes: ['Avoid pain, injury, or any area that does not feel safe to tense.'],
  },
  {
    id: 'meditation',
    toolId: '5',
    title: 'Meditation',
    family: 'body',
    module: '2.4',
    status: 'ready',
    format: 'timer',
    route: `${ROUTES.TOOLS}/5`,
    durationLabel: 'timer',
    bestFor: ['daily_practice', 'clarity', 'sound_observation'],
    bodySignals: ['Numbness', 'Muscle tension', 'Shallow breathing'],
    discreteness: 'low',
    energyLevel: 'low',
    solfeggio: 'slate',
    summary: 'Sit, observe, and return without forcing yourself to be calm.',
    steps: ['Choose one point of focus.', 'Notice when attention moves.', 'Return without criticism.'],
    safetyNotes: ['Short practice is enough. Sleepiness or distraction is not failure.'],
  },
  {
    id: 'mimicry-bridge',
    title: 'Mimicry as Regulation',
    family: 'senses',
    module: '2.4',
    status: 'learn',
    format: 'learning-guide',
    route: `${ROUTES.REGULATION_TOOLKIT}/mimicry-bridge`,
    durationLabel: 'guide',
    bestFor: ['shame', 'understanding', 'bridge_practice'],
    bodySignals: ['Jaw tension', 'Fists clenching'],
    discreteness: 'medium',
    energyLevel: 'low',
    solfeggio: 'violet',
    summary: 'A shame-free explanation of why mimicking can feel regulating.',
    steps: ['Notice the impulse without judging it.', 'Name that your body is trying to regain control.', 'Choose a quieter bridge practice.'],
    safetyNotes: ['This is an education guide, not something you have to practise.'],
  },
];
