import { BackButton } from '@/components/ui';

export default function TermsPage() {
  return (
    <div className="px-6 py-8 pb-32 max-w-2xl mx-auto" style={{ animation: 'fadeIn 0.61s ease-out' }}>
      <div className="flex items-center gap-3 mb-8">
        <BackButton />
        <h1
          className="text-2xl text-white"
          style={{ fontFamily: "'Josefin Sans', sans-serif", fontWeight: 200 }}
        >
          Terms of Service
        </h1>
      </div>

      <p className="text-xs text-slate-400 font-light mb-8">Last updated: February 2026</p>

      <div className="space-y-8">
        <section>
          <h2 className="text-lg text-white font-light mb-3">What MisoCalm is</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            MisoCalm is a personal tool for understanding and managing misophonia. It helps you
            track triggers, build coping skills, and reflect on your experiences. It is not a
            medical device, not therapy, and not a substitute for professional mental health support.
            If you are struggling, we encourage you to seek help from a qualified professional.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">AI companion</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            MisoCalm includes an AI chat companion designed to offer supportive conversation about
            misophonia. This companion is not a therapist, counsellor, or medical professional. Its
            responses are generated by AI and should not be treated as professional advice.
          </p>
          <p className="mt-3 text-sm text-slate-200 font-light leading-relaxed">
            If you are in crisis or experiencing thoughts of self-harm, please contact emergency
            services or the{' '}
            <span className="text-white">988 Suicide and Crisis Lifeline</span>{' '}
            (call or text 988 in the US).
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">Your account</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            You are responsible for keeping your account secure. Each account is intended for a single
            person. Please do not share your login credentials with others. If you believe your
            account has been compromised, contact us right away.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">Subscriptions</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            Some features of MisoCalm require a premium subscription, managed through Stripe. You
            can cancel your subscription at any time from within the app. Refunds are handled in
            accordance with applicable app store guidelines and our refund policy.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">Acceptable use</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            Please use MisoCalm for its intended purpose. You agree not to:
          </p>
          <ul className="mt-3 space-y-2 text-sm text-slate-200 font-light list-disc list-inside">
            <li>Attempt to reverse-engineer or tamper with the app</li>
            <li>Use the AI companion for harmful, abusive, or illegal purposes</li>
            <li>Create multiple accounts to circumvent restrictions</li>
            <li>Misrepresent yourself or impersonate others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">Limitation of liability</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            MisoCalm is provided as-is, without warranties of any kind. We do our best to make the
            app helpful and reliable, but we are not liable for decisions made based on app content
            or AI responses. Your use of MisoCalm is at your own discretion.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">Changes to these terms</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            We may update these terms from time to time. If we make significant changes, we will let
            you know through the app or by email. Continued use of MisoCalm after changes take effect
            means you accept the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-light mb-3">Contact</h2>
          <p className="text-sm text-slate-200 font-light leading-relaxed">
            If you have questions about these terms, reach out to us at{' '}
            <a href="mailto:support@misocalm.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">
              support@misocalm.com
            </a>
          </p>
        </section>

        <div className="pt-4 border-t border-slate-800">
          <p className="text-xs text-slate-400 font-light leading-relaxed">
            Last reviewed February 2026. If you have questions, reach out at the email above.
          </p>
        </div>
      </div>
    </div>
  );
}
